/**
 * Expo config plugin for the vendored Ferrostar native binding.
 *
 * Deliberately thin. React Native autolinking already finds the binding —
 * mobile/vendor/ferrostar/uniffi ships a podspec, an android/build.gradle,
 * and a react-native.config.js, and npm links it into node_modules like any
 * other dependency. There is nothing for a plugin to wire up.
 *
 * What a plugin *can* do, and what this one does, is fail `expo prebuild`
 * loudly on the two mistakes that otherwise surface as a crash on a rider's
 * phone:
 *
 *   1. The vendored Rust binary for the platform being built is missing.
 *      The TypeScript resolves and the app compiles either way.
 *   2. The New Architecture is off. The binding is a TurboModule generated by
 *      uniffi-bindgen-react-native; without the new architecture it is never
 *      registered, and the error reads as a missing module.
 *
 * See mobile/vendor/README.md for how the binaries get here.
 */
const fs = require('node:fs');
const path = require('node:path');

const VENDOR_DIR = path.join(__dirname, '..', 'vendor', 'ferrostar');

// One representative artifact per platform. Both are outputs of `ubrn build`
// and are absent together, so checking one file per platform is enough.
const PLATFORM_ARTIFACTS = {
  android: 'uniffi/android/src/main/jniLibs/arm64-v8a/libferrostar.so',
  ios: 'uniffi/FerrostarRN.xcframework/Info.plist',
};

const defaultExists = (relativePath) => fs.existsSync(path.join(VENDOR_DIR, relativePath));

/**
 * Throws unless the vendored binary for `platform` is present.
 * `exists` is injected for testing.
 */
function assertVendoredBinaries(platform, exists = defaultExists) {
  const artifact = PLATFORM_ARTIFACTS[platform];
  if (!artifact) throw new Error(`Unknown platform: ${platform}`);

  if (!exists('uniffi/package.json')) {
    throw new Error(
      'Ferrostar is not vendored: mobile/vendor/ferrostar/uniffi is empty.\n' +
        'Run mobile/vendor/build-ferrostar.sh, or download the artifacts from the\n' +
        '"Vendor Ferrostar" workflow. See mobile/vendor/README.md.'
    );
  }

  if (!exists(artifact)) {
    throw new Error(
      `Ferrostar's ${platform} binary is missing (${artifact}).\n` +
        `The app will compile without it and then fail to load the binding at\n` +
        `runtime. Rebuild it with:\n\n` +
        `    mobile/vendor/build-ferrostar.sh ${platform}\n`
    );
  }
}

/**
 * Ensures `newArchEnabled` is on, but never flips an explicit opt-out —
 * turning someone's deliberate `false` back to `true` behind their back would
 * trade a clear error for a confusing build.
 */
function requireNewArchitecture(properties) {
  if (properties.newArchEnabled === false) {
    throw new Error(
      'Ferrostar\'s binding is a TurboModule and requires the New Architecture,\n' +
        'but newArchEnabled is explicitly false. Remove that opt-out, or drop the\n' +
        'withFerrostar plugin from app.json.'
    );
  }
  return { ...properties, newArchEnabled: true };
}

/**
 * The plugin itself. Uses only the config-plugins API surface that is stable
 * across SDK versions: mods that read and rewrite the two properties files
 * prebuild generates.
 */
function withFerrostar(config) {
  const {
    withGradleProperties,
    withPodfileProperties,
  } = require('expo/config-plugins');

  config = withGradleProperties(config, (cfg) => {
    assertVendoredBinaries('android');
    // gradle.properties is modelled as a list of {type, key, value} items.
    const existing = cfg.modResults.find(
      (item) => item.type === 'property' && item.key === 'newArchEnabled'
    );
    requireNewArchitecture(existing?.value === 'false' ? { newArchEnabled: false } : {});
    cfg.modResults = cfg.modResults.filter(
      (item) => !(item.type === 'property' && item.key === 'newArchEnabled')
    );
    cfg.modResults.push({ type: 'property', key: 'newArchEnabled', value: 'true' });
    return cfg;
  });

  config = withPodfileProperties(config, (cfg) => {
    assertVendoredBinaries('ios');
    requireNewArchitecture(
      cfg.modResults.newArchEnabled === 'false' ? { newArchEnabled: false } : {}
    );
    cfg.modResults.newArchEnabled = 'true';
    return cfg;
  });

  return config;
}

module.exports = withFerrostar;
module.exports.assertVendoredBinaries = assertVendoredBinaries;
module.exports.requireNewArchitecture = requireNewArchitecture;
