const {
  assertVendoredBinaries,
  requireNewArchitecture,
} = require('../withFerrostar');

describe('assertVendoredBinaries', () => {
  const present = {
    'uniffi/package.json': true,
    'uniffi/android/src/main/jniLibs/arm64-v8a/libferrostar.so': true,
    'uniffi/FerrostarRN.xcframework/Info.plist': true,
  };
  const exists = (files) => (p) => Boolean(files[p]);

  it('passes when both platforms have vendored binaries', () => {
    expect(() => assertVendoredBinaries('android', exists(present))).not.toThrow();
    expect(() => assertVendoredBinaries('ios', exists(present))).not.toThrow();
  });

  // The whole point of this check: the TypeScript resolves and the app builds
  // whether or not the Rust binary is there, so a missing .so surfaces as a
  // runtime crash on a rider's phone unless prebuild refuses first.
  it('fails prebuild, naming the platform and the rebuild command', () => {
    const noAndroid = { ...present };
    delete noAndroid['uniffi/android/src/main/jniLibs/arm64-v8a/libferrostar.so'];

    expect(() => assertVendoredBinaries('android', exists(noAndroid))).toThrow(
      /android.*vendor\/build-ferrostar\.sh/s
    );
  });

  it('checks only the platform being prebuilt', () => {
    const iosOnly = { 'uniffi/package.json': true, 'uniffi/FerrostarRN.xcframework/Info.plist': true };
    expect(() => assertVendoredBinaries('ios', exists(iosOnly))).not.toThrow();
    expect(() => assertVendoredBinaries('android', exists(iosOnly))).toThrow();
  });
});

describe('requireNewArchitecture', () => {
  // Ferrostar's binding is a TurboModule generated by uniffi-bindgen-react-
  // native. On the old architecture it is not registered at all, and the
  // failure looks like a missing module rather than a config mistake.
  it('turns the flag on when it is missing', () => {
    expect(requireNewArchitecture({})).toEqual({ newArchEnabled: true });
  });

  it('leaves an already-enabled project alone', () => {
    expect(requireNewArchitecture({ newArchEnabled: true, other: 1 })).toEqual({
      newArchEnabled: true,
      other: 1,
    });
  });

  it('refuses to silently re-enable a project that opted out', () => {
    expect(() => requireNewArchitecture({ newArchEnabled: false })).toThrow(
      /TurboModule/
    );
  });
});
